interface WheatIconProps {
  size?: number;
  className?: string;
}

const WheatIcon = ({ size = 32, className = "" }: WheatIconProps) => {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 32 32"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
    >
      {/* Колос слева */}
      <path
        d="M8 4C8 4 6 6 6 8C6 10 8 12 8 12C8 12 6 14 6 16C6 18 8 20 8 20C8 20 6 22 6 24C6 26 8 28 8 28"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        fill="none"
      />

      {/* Зерна левого колоса */}
      <ellipse
        cx="7"
        cy="7"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="9"
        cy="8"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="7"
        cy="11"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="9"
        cy="12"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="7"
        cy="15"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="9"
        cy="16"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="7"
        cy="19"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="9"
        cy="20"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="7"
        cy="23"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="9"
        cy="24"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />

      {/* Центральный колос */}
      <path
        d="M16 2C16 2 14 4 14 6C14 8 16 10 16 10C16 10 14 12 14 14C14 16 16 18 16 18C16 18 14 20 14 22C14 24 16 26 16 26C16 26 14 28 14 30"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        fill="none"
      />

      {/* Зерна центрального колоса */}
      <ellipse
        cx="15"
        cy="5"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.9"
      />
      <ellipse
        cx="17"
        cy="6"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.9"
      />
      <ellipse
        cx="15"
        cy="9"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.9"
      />
      <ellipse
        cx="17"
        cy="10"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.9"
      />
      <ellipse
        cx="15"
        cy="13"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.9"
      />
      <ellipse
        cx="17"
        cy="14"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.9"
      />
      <ellipse
        cx="15"
        cy="17"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.9"
      />
      <ellipse
        cx="17"
        cy="18"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.9"
      />
      <ellipse
        cx="15"
        cy="21"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.9"
      />
      <ellipse
        cx="17"
        cy="22"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.9"
      />
      <ellipse
        cx="15"
        cy="25"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.9"
      />
      <ellipse
        cx="17"
        cy="26"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.9"
      />

      {/* Колос справа */}
      <path
        d="M24 4C24 4 26 6 26 8C26 10 24 12 24 12C24 12 26 14 26 16C26 18 24 20 24 20C24 20 26 22 26 24C26 26 24 28 24 28"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        fill="none"
      />

      {/* Зерна правого колоса */}
      <ellipse
        cx="25"
        cy="7"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="23"
        cy="8"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="25"
        cy="11"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="23"
        cy="12"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="25"
        cy="15"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="23"
        cy="16"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="25"
        cy="19"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="23"
        cy="20"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="25"
        cy="23"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />
      <ellipse
        cx="23"
        cy="24"
        rx="1.5"
        ry="1"
        fill="currentColor"
        opacity="0.8"
      />

      {/* Стебли */}
      <path
        d="M8 28L12 32"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        opacity="0.6"
      />
      <path
        d="M16 30L16 32"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        opacity="0.6"
      />
      <path
        d="M24 28L20 32"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        opacity="0.6"
      />
    </svg>
  );
};

export default WheatIcon;
